// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvUn92KjIyTtqSL7UOn6X5-3o6oVCzixc',
    appId: '1:1052037114353:web:b58585382d660c596abc50',
    messagingSenderId: '1052037114353',
    projectId: 'fir-series-251f8',
    authDomain: 'fir-series-251f8.firebaseapp.com',
    storageBucket: 'fir-series-251f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmJq2L_cLHcBGUHIQLdBcEiI1kmYaWgog',
    appId: '1:1052037114353:android:fea2225d9c4d036e6abc50',
    messagingSenderId: '1052037114353',
    projectId: 'fir-series-251f8',
    storageBucket: 'fir-series-251f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr3uPumyGz5thgySap9VBxnVGA-aPpLAQ',
    appId: '1:1052037114353:ios:aebd1309fe46d8106abc50',
    messagingSenderId: '1052037114353',
    projectId: 'fir-series-251f8',
    storageBucket: 'fir-series-251f8.appspot.com',
    iosBundleId: 'com.example.firebaseSeries',
  );
}
