// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQw3i286-YQmidYYQJaF5vRjBEbG3I96A',
    appId: '1:752850897548:web:11a14f1705481face8c9a9',
    messagingSenderId: '752850897548',
    projectId: 'attendance-management-sy-5bf5c',
    authDomain: 'attendance-management-sy-5bf5c.firebaseapp.com',
    storageBucket: 'attendance-management-sy-5bf5c.appspot.com',
    measurementId: 'G-BJ72DJYK5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEoohbCZ3zc--9Iz8Mbkl9O8Hq-znX0-I',
    appId: '1:752850897548:android:674998b6877e312ee8c9a9',
    messagingSenderId: '752850897548',
    projectId: 'attendance-management-sy-5bf5c',
    storageBucket: 'attendance-management-sy-5bf5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQGhTgpIin7trodEqCKgWZIJlrMfgqnfQ',
    appId: '1:752850897548:ios:013601d09bf03624e8c9a9',
    messagingSenderId: '752850897548',
    projectId: 'attendance-management-sy-5bf5c',
    storageBucket: 'attendance-management-sy-5bf5c.appspot.com',
    iosBundleId: 'com.example.firebaseSeries',
  );
}
